export const ERRORS = {
    INVALID_DATA: "invalid_data",
    PLAYER_ALREADY_IN_GAME: "player_already_in_game",
    ROOM_NOT_FOUND: "room_not_found",
    PLAYER_NOT_IN_GAME: "player_not_in_game",
    GAME_ALREADY_STARTED: "game_already_started",
    GAME_FULL: "game_full",
    USERNAME_TAKEN: "username_taken",
    NOT_ENOUGH_PLAYERS: "not_enough_players",
    NO_ADJACENT_CELLS_OWNED: "no_adjacent_cells_owned",
    NOT_ENOUGH_MONEY: "not_enough_money",
    NOT_ENOUGH_MATERIALS: "not_enough_materials",
    BUILDING_NOT_FOUND: "building_not_found",
    NO_REQUIRED_BUILDING: "no_required_building",
    OUT_OF_BOUNDS: "out_of_bounds",
    PORT_ERROR: "port_error",
    CELL_OCCUPIED: "cell_occupied",
    CELL_NOT_OWNED: "cell_not_owned",
    CELL_NOT_A_BUILDING: "cell_not_a_building",
    CANNOT_PLACE_TOWN_HALL: "cannot_place_town_hall",
    CANNOT_DELETE_TOWN_HALL: "cannot_delete_town_hall",
    UNEXPECTED_BUILDING_BOUNDS: "unexpected_building_bounds",
    HOST_FEATURE: "host_feature",
    SELF_NUKE: "self_nuke",
    TARGET_NOT_FOUND: "target_not_found",
    GAME_NOT_STARTED: "game_not_started",
    INVALID_GAME_MODE: "invalid_game_mode", // When the game mod isn't in the switch in Game.ts. Ask the client to choose another mode.
    UNKNOWN_ERROR: "unknown_error"
} as const;