export const POPULATION_POOL = 300;
export const MIN_POPULATION = 2;
export const POPULATION_POOL_PERCENT_MIN = 50;
export const POPULATION_POOL_PERCENT_MAX = 100;
export const POPULATION_POOL_PERCENT_DEFAULT = 100;